### ISSUE TITLE
CustomSwitch1 does not show Text on right side on iOS

### ISSUE THREAD

**Issue by danheinz** [IeuanWalker/Maui.Switch#11]
When the switch is toggled left (off) all text shows correctly.  When the switch is toggled to the right, the text on the knob disappears.
I've only tested this on iOS 15.0 on an iPhone 12 Pro Simulator so far.  This is not an issue on Android.
Here is a short video of the issue:
https://app.screencast.com/HDcO79YkiOvE5?conversation=B9WZApSOeY9gXKXsqdiRbI

**Comment by danheinz** [comment]
Thanks!  I'll try to look at it when I have time.  I used the MAUI Toggle for now, which is not ideal for my needs, so I have an incentive to see if I can fix this.

**Comment by IeuanWalker** [comment]
@danheinz thats great thanks

**Comment by IeuanWalker** [comment]
@danheinz im hoping this will fix it, looks like its been added too the .net 8 release - https://github.com/dotnet/maui/issues/10724

**Comment by AlexandrNikulin** [comment]
Unfortunately it still does not work on iOS. Tested on iOS 17 (.net 8)

**Comment by AlexandrNikulin** [comment]
@IeuanWalker Any workarounds?

**Comment by IeuanWalker** [comment]
@AlexandrNikulin ahh that's annoying

Not that i know of sorry.

Might need some platform specific code / handler work to make the border control behave the same as the frame control did in XF

I dont have much time these days, but am open to PRs

**Comment by IeuanWalker** [comment]
@AlexandrNikulin  Tested using the latest .NET 8 release and iOS now looks and behaves like android :)
